# Generated by Django 5.1.15 on 2026-10-07 20:59

import django.db.models.functions.text
from django.db import migrations, models

import apps.consents.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Terms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("terms", "Terms of use"), ("marketing", "Marketing")],
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(validators=[apps.consents.validators.validate_content]),
                ),
                (
                    "version",
                    models.CharField(
                        max_length=20, validators=[apps.consents.validators.validate_version]
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[
                            ("es", "Español"),
                            ("pt-BR", "Português (Brasil)"),
                            ("en", "English"),
                        ],
                        max_length=5,
                        validators=[apps.consents.validators.validate_locale],
                    ),
                ),
                ("requires_reacceptance", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "legal document",
                "verbose_name_plural": "legal documents",
                "constraints": [
                    models.UniqueConstraint(
                        models.F("kind"),
                        django.db.models.functions.text.Lower("version"),
                        models.F("locale"),
                        name="consents_terms_version_ci_unique",
                        violation_error_message="A document of this kind with this version and language already exists.",
                    )
                ],
            },
        ),
    ]
