# Generated by Django 5.1.15 on 2026-10-07 21:11

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.consents.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Terms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("terms", "Terms of use"), ("marketing", "Marketing")],
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(validators=[apps.consents.validators.validate_content]),
                ),
                (
                    "version",
                    models.CharField(
                        max_length=20, validators=[apps.consents.validators.validate_version]
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[
                            ("es", "Español"),
                            ("pt-BR", "Português (Brasil)"),
                            ("en", "English"),
                        ],
                        max_length=5,
                        validators=[apps.consents.validators.validate_locale],
                    ),
                ),
                ("requires_reacceptance", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "legal document",
                "verbose_name_plural": "legal documents",
                "constraints": [
                    models.UniqueConstraint(
                        models.F("kind"),
                        django.db.models.functions.text.Lower("version"),
                        models.F("locale"),
                        name="consents_terms_version_ci_unique",
                        violation_error_message="A document of this kind with this version and language already exists.",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("user_email_hash", models.CharField(editable=False, max_length=64)),
                ("terms_accepted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "terms",
                    models.ForeignKey(
                        limit_choices_to={"kind": "terms"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="consents.terms",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terms_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "terms acceptance",
                "verbose_name_plural": "terms acceptances",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("user", "terms"),
                        name="consents_userterms_active_unique",
                        violation_error_message="This user has already accepted this document.",
                    )
                ],
            },
        ),
    ]
