# Generated by Django 5.1.15 on 2026-10-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consents", "0002_support_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmarketingconsent",
            name="user",
        ),
        migrations.RemoveField(
            model_name="historicaluserterms",
            name="user",
        ),
    ]
