# Generated by Django 5.1.15 on 2026-10-06 14:20

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_historicaluser"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=150)),
                ("birthdate", models.DateField()),
                ("country", models.CharField(max_length=2)),
                ("public_id", models.CharField(max_length=64, unique=True)),
                ("code_hash", models.CharField(max_length=64)),
                ("code_expires_at", models.DateTimeField()),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("code_validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        name="accounts_pendingregistration_email_ci_unique",
                        violation_error_message="A pending registration with this email already exists.",
                    )
                ],
            },
        ),
    ]
